# Generated by Django 4.0.1 on 2022-01-26 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project_access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': '1. Доступ к проекту',
            },
        ),
        migrations.CreateModel(
            name='Project_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': '2. Тип проекта',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='проект')),
                ('deal_sence', models.TextField(verbose_name='суть')),
                ('deal_why', models.TextField(verbose_name='почему')),
                ('image', models.ImageField(null=True, upload_to='images/', verbose_name='фото')),
                ('price', models.PositiveIntegerField(verbose_name='сумма usd.')),
                ('investment_term', models.PositiveIntegerField(verbose_name='срок мес.')),
                ('income', models.PositiveIntegerField(verbose_name='% доходности')),
                ('address', models.CharField(max_length=512, verbose_name='адрес')),
                ('access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project_access')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project_type')),
            ],
            options={
                'verbose_name': 'проекты',
                'verbose_name_plural': 'проекты',
            },
        ),
    ]
